PREFIX era: <http://data.europa.eu/949/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>

SELECT DISTINCT ?startWKT ?endWKT ?speed
WHERE {
    ?sol a era:SectionOfLine .
    ?sol (era:hasPart|era:track) ?track .
    ?sol era:opStart/(^era:canonicalURI)?/(era:netReference)?/geo:hasGeometry/geo:asWKT ?startWKT .
    ?sol era:opEnd/(^era:canonicalURI)?/(era:netReference)?/geo:hasGeometry/geo:asWKT ?endWKT .
    ?track (era:belongsTo/era:subsetOf*)?/era:maximumPermittedSpeed ?speed .
}
