PREFIX era: <http://data.europa.eu/949/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?length ?height ?WKT
WHERE {
    ?op a era:OperationalPoint .
    ?op (era:hasPart|era:track) ?track .
    ?track (era:hasPart|era:platformEdge) ?pe .
    ?pe (era:belongsTo/era:subsetOf*)?/era:lengthOfPlatform ?length .
    ?pe (era:belongsTo/era:subsetOf*)?/era:platformHeight ?heightObj .
    ?heightObj skos:notation ?height .
    ?op (era:netReference)?/geo:hasGeometry/geo:asWKT ?WKT .
}
